package com.infoskillstechnology.fluperpaginationdemo.connection

class ApiConstants{
    companion object {

        const val EMAIL_PATTERN = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)\$"
        const val NUMBER_PATTERN = "^[0-9]*$"
        const val NAME_PATTERN = "[A-Za-z0-9]"
        const val imageBaseUrl = "http://3.130.38.251:3000"
        const val blockCharacterSet = "~#^|$%&*!"


        const val SUFFIX_SIGN_UP: String = "signup"
        const val SUFFIX_UPDATE_PROFILE: String = "createProfile"
        const val SUFFIX_LOGIN: String ="login"
        const val SUFFIX_SOCIAL_SIGNUP: String ="social_signup"
        const val SUFFIX_FORGOT_PASSWORD="forgetPassword"
        const val SUFFIX_RESET_PASSWORD="resetPassword"
        const val SUFFIX_OTP_VERIFICATION="verifyOtp"
        const val SUFFIX_GET_LANGUAGE="getlanguage"
        const val SUFFIX_GET_CURRENCY="getcurrency"
        const val SUFFIX_IS_SOCIAL_ACTIVE="is_social_active"
        const val SUFFIX_RESEND_OTP="resendOtp"
        const val SUFFIX_GET_COUNTRY_LIST="getstatichomedata"
        const val SUFFIX_ADD_ADDRESS="addaddress"
        const val SUFFIX_GET_ADDRESS_LIST="getuseraddress"
        const val SUFFIX_UPDATE_ADDRESS_DEFAULT="updateaddressdefault"
        const val SUFFIX_RESTAURANT_ACC_TO_CUISINE="resturantaccordingtocuisine"
        const val SUFFIX_RESTAURANT_DETAIL="getsingleresturantdetail"
        const val SUFFIX_CATEGORY_LIST="getcategoriesdata"
        const val SUFFIX_MENU_LIST="get_menu_item_byid"
        const val SUFFIX_MENU_DETAIL="get_singlemenu_item_byid"
        const val SUFFIX_ADD_TO_CART="addtocartitem"
        const val SUFFIX_GET_CART_DATA="get_cart_data"
        const val SUFFIX_ADD_TO_RECENT_SEARCH="addtorecentsearch"
        const val SUFFIX_GET_RECENT_SEARCH="get_recent_search"
        const val SUFFIX_GET_USER_FAV_RESTURANT_DATA="user_fav_resturant_data"
        const val SUFFIX_ADD_REMOVE_QUANTITY="add_remove_quantity"
        const val SUFFIX_GET_NEAREST_RES_FOR_SEARCH="get_nearest_res_for_search"
        const val SUFFIX_GET_CUISINE_NAME="get_cuisine_name"
        const val SUFFIX_FILTER_RESTAURANT="filter_restaurant"
        const val SUFFIX_GET_HOME_OFFER_DATA="get_home_offer_data"
        const val SUFFIX_GET_OFFER_DATA_ACC_SERVICE="get_offer_accto_service"
        const val SUFFIX_GET_SUBCAT_ACC_TO_CAT="get_subcate_acc_to_cat"
        const val SUFFIX_APPLY_COUPON="apply_coupan"
        const val SUFFIX_USER_PLACE_ORDER="user_place_order"
        const val SUFFIX_GET_MY_ORDER="get_my_order"
        const val SUFFIX_GET_SINGLE_PRODUCT_DATA="get_single_product_data"
        const val SUFFIX_POST_USER_RATING="post_user_rating"
        const val SUFFIX_LOGOUT="log_out"
        const val SUFFIX_REORDER_API="reorder_api"
        const val SUFFIX_UPDATE_CURBSIDE_STATUS="user_updates_cubside_status"
        const val SUFFIX_ADD_REMOVE_SPECIALITY="useraddremovespeciality"
        const val SUFFIX_USER_DATA="singleuserdata"
        const val SUFFIX_ADD_TO_FAV_REST="add_to_fav_rest"
        const val SUFFIX_MAKE_RESERVATION="make_reservation"
        const val SUFFIX_MY_RESERVATION="my_reservation"
        const val SUFFIX_USER_PAY_RESERVATION="user_pay_reservation"
        const val SUFFIX_SINGLE_MY_RESERVATION="single_my_reservation"
        const val SUFFIX_USER_ACCEPT_RESERVATION="user_accept_reservation"

        const val SUFFIX_DELETE_USER_CART="remove_all_the_data_fromcart"

        const val SUFFIX_USER_ADD_CARD_DETAILS="addPaymentDetails"
        const val SUFFIX_GET_CARD_LIST = "get_list_of_card"
        const val SUFFIX_REMOVE_CARD = "removeCard"
        const val SUFFIX_ADD_TO_WALLLET = "add_to_walllet"
        const val SUFFIX_GET_WALLETS_HISTORY = "get_wallets_history"
        const val SUFFIX_CHANGE_DEFAULT_CARD = "change_default_card"
        const val SUFFIX_UPDATE_PAYMENT_MODE = "update_payment_mode"
        const val SUFFIX_GET_MEMBER_CARD = "get_member_card"
        const val SUFFIX_UPLOAD_IMAGE = "upload_image"
        const val SUFFIX_SEND_CHAT_NOTIFICATION = "sendchatnotification"
        const val SUFFIX_ADD_COMMENTS_ON_DISH = "add_comments_on_dish"
        const val SUFFIX_GET_COMMENTS_ACCORDING_DISH = "get_comments_according_dish"
        const val SUFFIX_GET_COMMENTS_ACCORDING_RESTURANT = "get_comments_according_resturant"
        const val SUFFIX_ADD_REVIEW_ON_RESTURANT = "add_review_on_resturant"
        const val SUFFIX_SHARE_APP = "share_app"
        const val SUFFIX_GET_ADMIN_SPECIALITY = "getadminspeciality"

    }

}